CONTIKI_PROJECT = hello-world
all: $(CONTIKI_PROJECT)
CONTIKI=../../../..


MAKE_ROUTING = MAKE_ROUTING_RPL_CLASSIC
MAKE_MAC = MAKE_MAC_TSCH
MODULES += os/services/shell

include $(CONTIKI)/Makefile.include